name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (needed for Docker Build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t caffeine-backend .

      # Step 4: Log into Docker registry (if using one)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: laera.daniel@hotmail.com
          password: Only_for_me_2023

      # Step 5: Push the Docker image to the registry (if desired)
      - name: Push Docker image to registry
        run: |
          docker tag caffeine-backend laera.daniel@hotmail.com/caffeine-backend:latest
          docker push laera.daniel@hotmail.com/caffeine-backend:latest

      # Step 6: Deploy on server using SSH
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/caffeine-backend
            docker compose down || true
            docker compose up --build -d
            docker image prune -f
            docker ps